---
- name: Deploy Docker image from DockerHub to Kubernetes
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: Create a Kubernetes Deployment using Docker image
      copy:
        dest: /tmp/deployment.yaml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: cw2-server
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: cw2-server
            template:
              metadata:
                labels:
                  app: cw2-server
              spec:
                containers:
                  - name: cw2-server
                    image: euanscott16/cw2-server:1.0
                    ports:
                      - containerPort: 8080

    - name: Apply the deployment to Kubernetes
      command: kubectl apply -f /tmp/deployment.yaml
