- name: Install kubectl
  hosts: production
  become: yes
  tasks:
    - name: Download kubectl binary
      get_url:
        url: https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Verify kubectl installation
      shell: kubectl version --client
